# Generated by Django 5.0.4 on 2026-05-20 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('BANOS_H', 'Baños Hombres'), ('BANOS_M', 'Baños Mujeres'), ('AREAS_V', 'Áreas Verdes')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=1)),
                ('posicion_cola_banos', models.IntegerField(default=0)),
                ('posicion_cola_verdes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('area_permitida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('usuario_creado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigo_origen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_asignada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno_horario', models.CharField(choices=[('TARDE', 'Tarde (2:00 PM)'), ('NOCHE', 'Noche')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CUMPLIDO', 'Cumplido'), ('FALTO', 'No Cumplido')], default='PENDIENTE', max_length=10)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='ExcepcionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('turno', models.CharField(choices=[('TARDE', 'Tarde (2:00 PM)'), ('NOCHE', 'Noche')], max_length=10)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='core.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'dia_semana', 'turno')},
            },
        ),
    ]
