# Generated by Django 5.0.4 on 2026-05-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estudiante_carnet_estudiante_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='carnet',
            field=models.CharField(max_length=30),
        ),
    ]
