# Generated by Django 5.0.4 on 2026-05-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historialaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(choices=[('BANOS_H', 'Baños Hombres'), ('BANOS_M', 'Baños Mujeres'), ('AREAS_V', 'Áreas Verdes'), ('JARDINES', 'Jardines Internos')], max_length=10, unique=True),
        ),
    ]
