# Generated by Django 5.0.4 on 2026-05-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cargar_jardines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excepcionhorario',
            name='turno',
            field=models.CharField(choices=[('MANANA', 'Mañana (6:00 AM)'), ('TARDE', 'Tarde (2:00 PM)'), ('NOCHE', 'Noche')], max_length=10),
        ),
        migrations.AlterField(
            model_name='turnoasignado',
            name='turno_horario',
            field=models.CharField(choices=[('MANANA', 'Mañana (6:00 AM)'), ('TARDE', 'Tarde (2:00 PM)'), ('NOCHE', 'Noche')], max_length=10),
        ),
    ]
