# Generated by Django 5.0.4 on 2026-05-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_excepcionhorario_dia_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excepcionhorario',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')]),
        ),
    ]
